Default: &defaults
  database: darkchess.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: darkchess_test.sqlite3
  <<: *defaults

Staging:
  database: darkchess_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: darkchess_production.sqlite3
  poolsize: 100
  <<: *defaults
